<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Save User
     */
    public function saveUser()
    {
        if(empty($this->password)) {
            throw new Exception(sprintf("Value password haven't was empty"));
        }

        if(empty($this->username)) {
            throw new Exception(sprintf("Value username haven't was empty"));
        }

        $em = $this->getDoctrine()->getManager();
        $em->persist($this);
        $em->flush();
    }
}
